apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq
spec:
  selector:
    matchLabels:
      app: rmq
  template:
    metadata:
      labels:
        app: rmq
    spec:
      containers:
        - name: rmq
          image: "rabbitmq:3-management"
