apiVersion: v1
kind: Service
metadata:
  name: rmq
spec:
  type: NodePort
  selector:
    app: rmq
  ports:
    - name: http
      port: 15672
      targetPort: 15672
      nodePort: 32000
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 32001
